spring.application.name = MoRIS Desktop
spring.application.home = ${MORIS_HOME}
spring.application.i18n = i18n.moris
spring.application.style = /styles/moris.css

spring.main.web-application-type = none

spring.datasource.driver-class-name = org.mariadb.jdbc.Driver
spring.sql.init.mode = always
spring.jpa.hibernate.ddl-auto = update
